[build]
  publish = "public"
  command = "pip install -r requirements.txt"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-core-python"
